repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude_types: [csv, tsv]
    -   id: trailing-whitespace
        exclude_types: [csv, tsv]
-   repo: local
    hooks:
    -   id: zimports
        name: zimports
        entry: poetry run zimports -m covsonar,tests
        language: system
        types: [python]
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
