-- MySQL Script generated by MySQL Workbench
-- Sa 27 Feb 2021 09:21:34 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sequence` (
  `seqID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sequence` TEXT NOT NULL,
  PRIMARY KEY (`seqID`),
  UNIQUE INDEX `id_UNIQUE` (`seqID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genome` (
  `genomeID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `accession` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `seqID` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`genomeID`),
  UNIQUE INDEX `id_UNIQUE` (`genomeID` ASC) VISIBLE,
  INDEX `fk_genome2sequence_idx` (`seqID` ASC) VISIBLE,
  CONSTRAINT `fk_genome2sequence`
    FOREIGN KEY (`seqID`)
    REFERENCES `mydb`.`sequence` (`seqID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`variants` (
  `varID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ref` BIGINT UNSIGNED NOT NULL,
  `alt` VARCHAR(45) NULL,
  `refpos` VARCHAR(45) NULL,
  `level` ENUM("nuc", "aa") NULL,
  PRIMARY KEY (`varID`),
  UNIQUE INDEX `id_UNIQUE` (`varID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seq2var`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seq2var` (
  `varID` BIGINT UNSIGNED NOT NULL,
  `seqID` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_seq2seqvar` (`seqID` ASC) VISIBLE,
  PRIMARY KEY (`seqID`, `varID`),
  CONSTRAINT `fk_seq2seqvar`
    FOREIGN KEY (`seqID`)
    REFERENCES `mydb`.`sequence` (`seqID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_var2seqvar`
    FOREIGN KEY (`varID`)
    REFERENCES `mydb`.`variants` (`varID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lineage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lineage` (
  `seqID` BIGINT UNSIGNED NOT NULL,
  `lineage` VARCHAR(45) NOT NULL,
  `pangolin_version` VARCHAR(45) NOT NULL,
  `pangolearn_version` VARCHAR(45) NOT NULL,
  INDEX `fk_sequence2lineage` (`seqID` ASC) VISIBLE,
  CONSTRAINT `fk_sequence2lineage`
    FOREIGN KEY (`seqID`)
    REFERENCES `mydb`.`sequence` (`seqID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
