name: Release
on:
  release:
    types: [published]
    tags-ignore:
      - '!v2.*'
jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: x64
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        activate-environment: covsonar
        channels: conda-forge,bioconda,defaults
        channel-priority: true
    - run: pip install nox==2023.4.22
    - run: pip install poetry==1.5.1
    - run: nox
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
