name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniforge-variant: Mambaforge
        channels: conda-forge,bioconda,defaults
        python-version: 3.9
        activate-environment: covsonar
        use-mamba: true
    - run: pip install nox==2023.4.22
    - run: pip install poetry==1.5.1
    - run: nox
